<?php

namespace SoftUniBlogBundle\Repository;

/**
 * ArticleeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleeRepository extends \Doctrine\ORM\EntityRepository
{
}
